networks:
  nuxt:
    driver: bridge

services:
  nginx:
    build: 
      context: .
      dockerfile: dockerfile.nginx  # Dockerfile for building nginx image
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf from host
    ports:
      - "80:80"  # Expose port 80 on host
    container_name: nuxt-nginx  # Container name for nginx
    networks:
      - nuxt  # Connect to the 'nuxt' network
    restart: always  # Restart policy

  nuxtjs:
    build:
      context: .
      dockerfile: dockerfile.nuxtjs  # Dockerfile for building nuxtjs image
    ports:
      - "3000:3000"  # Expose port 3000 on host
    container_name: nuxt-js  # Container name for nuxtjs
    command: ["yarn", "run", "buildStart"]  # Command to start nuxtjs (adjust as per your setup)
    networks:
      - nuxt  # Connect to the 'nuxt' network
    restart: always  # Restart policy
